---
# Source: website/templates/drupal/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
spec:
  minReadySeconds: 60
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
        version: "790054547"
    spec:
      containers:
        - name: drupal
          image: "drupal:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 4
              memory: 4Gi
              ephemeral-storage: 4Gi
            limits:
              cpu: 4
              memory: 4Gi
              ephemeral-storage: 4Gi
---
# Source: website/templates/drupal/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: drupal-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drupal-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
